name: Esquio Docker UI Continous Deployment
on: 
  push:
    tags:       
      - ui-release-*  # Push events to release-* 
env:
  TAG: 3.0.${{ github.run_id }}
  IMAGE_NAME: esquioui
  ESQUIO_REPO: xabarilcoding
jobs:  
  docker_build_publish:    
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        name: ${{ env.ESQUIO_REPO }}/${{ env.IMAGE_NAME }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: ./build/UIDockerfile
        tags: "latest,${{ env.TAG }}"

  docker_azure_deploy:
    env:
      APP_NAME: esquiodemoui
    needs: docker_build_publish
    name: DockerDeploy
    runs-on: ubuntu-latest
    steps:    
    - uses: azure/login@v1
      with:
        creds: '${{ secrets.SPN_ESQUIO }}'
    - name: Azure App Service Settings
      uses: Azure/appservice-settings@v1
      with:
        app-name: ${{ env.APP_NAME }}     
        app-settings-json: '${{ secrets.APPSETTINGS_ESQUIO_UI_APP }}'
    - uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.APP_NAME }}
        images: '${{ env.ESQUIO_REPO }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}'